### ISSUE TITLE
This project is up for adoption

### ISSUE THREAD

**Issue by patrickayoup** [patrickayoup/virtualbox-guest-additions-cookbook#2]

**Comment by rishabhtulsian** [comment]
I can adopt it

**Comment by patrickayoup** [comment]
@rishabhtulsian sure; I will do the transfer tonight.

Thanks

**Comment by patrickayoup** [comment]
@rishabhtulsian Could you please provide me with your username on supermarket.chef.io?

**Comment by rishabhtulsian** [comment]
rishabhtulsian
